### ISSUE TITLE
error

### ISSUE THREAD

**Issue by lorena-barberia** [StataAficionado/covid-19-stata-import#2]
I tried to install and execute the ado per the instructions, but it did not complete. The ado stopped  after saving a file for each date in the documents file.

**Comment by StataAficionado** [comment]
You need to check the syntax, it requires you to specify some countries and a few options.
But once you have the files, you can basically have fun on your own.

Kind regards,
Koenraad


On 25 Mar 2020, at 14:50, Lorena G Barberia <notifications@github.com<mailto:notifications@github.com>> wrote:



I tried to install and execute the ado per the instructions, but it did not complete. The ado stopped after saving a file for each date in the documents file.

**Comment by StataAficionado** [comment]
If you type -covid- , the usage mode appears in the results window.

**Comment by lorena-barberia** [comment]
Thanks Koenraad! I tried it, and so did my TA. Neither were able to make it run.  I copied the ado in my personal directory. When I type covid or covid19, I get the following message: command covid is unrecognized r(199). I tried cd C:\ado\personal first, but this still did not work.
